[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tsrc/linker.ld"]

runner = "qemu-system-riscv64 -machine virt -nographic -bios none -kernel"

[term]
verbose = true
